imports:
    - { resource: parameters.yml }

monolog:
    handlers:
        main:
            type:  stream
            path:  %site.path_www%/app/logs/logs.log
            level: debug

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     %database.host%
        port:     %database.port%
        dbname:   %database.name%
        user:     %database.user%
        password: %database.password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            ContentBlocksBundle:
                type: annotation
                prefix: ForkCMS\Bundle\ContentBlocksBundle\Entity
                dir: /Users/jelmersnoeck/Projects/ContentBlocks/Entity

services:
    database:
        class: SpoonDatabase
        arguments:
            - %database.driver%
            - %database.host%
            - %database.user%
            - %database.password%
            - %database.name%
            - %database.port%
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8' } ] ]